version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build: .
    container_name: aspnetcore_sample
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
## http://localhost:8080/swagger/index.html
